### ISSUE TITLE
how to support jsonrpc2.0 batch 

### ISSUE THREAD

**Issue by sighWang** [shogowada/json-rpc-2.0#25]
I have call jsonrpcserver with valid Batch, But there is `error: { code: -32600, message: 'Invalid Request' }` return to me

**Comment by shogowada** [comment]
Thanks for the catch. It doesn't support bulk requests as of now but let me add it!

**Comment by shogowada** [comment]
I think it actually requires a breaking change, so let me think it for a while.

In the meantime, you can workaround it by doing something like this:
```javascript
const jsonRPCServer = new JSONRPCServer();

app.post("/json-rpc", async (req, res) => {
  const request = req.body;
  if (Array.isArray(request)) {
    const responses = await Promise.all(request.map(request => jsonRPCServer.receive(request)));
    res.json(responses);
  } else {
    const response = await jsonRPCServer.receive(request);
    res.json(response);
  }
});
```
