### ISSUE TITLE
JSONRPCParams type is incomplete

### ISSUE THREAD

**Issue by samherrmann** [shogowada/json-rpc-2.0#28]
The `JSONRPCParams` type definition does not allow all valid JSON values. The current type definition is as follows:

```ts
export type JSONRPCParams = object | any[];
```
Source: https://github.com/shogowada/json-rpc-2.0/blob/v1.0.0/src/models.ts#L5

The following are other valid JSON values that should be allowed by `JSONRPCParams`:

Number:
```json
{ "params": 123 }
```

String:
```json
{ "params": "foo" }
```
Boolean:
```json
{ "params": true }
```

See [JSON spec](https://www.json.org/json-en.html).

One suggestion is for the `JSONRPCParams` type definition to look something like this:

```ts
export type JSONRPCParams = object | any[] | number | string | boolean;
```

**Comment by shogowada** [comment]
Thanks for raising the issue!

This library follows JSON-RPC 2.0 spec. While the type definition doesn't allow all valid JSON values, it should allow all valid JSON-RPC 2.0 param types: https://www.jsonrpc.org/specification#request_object

> 4.2 Parameter Structures
> If present, parameters for the rpc call MUST be provided as a Structured value. Either by-position through an Array or by-name through an Object.

Closing it as non-issue, but let me know if I'm missing something 🙂

**Comment by samherrmann** [comment]
I definitely missed [section 4.2 of the specification](https://www.jsonrpc.org/specification#parameter_structures). 😟
