### ISSUE TITLE
Question: mapErrorToJSONRPCErrorResponse vs exception middleware

### ISSUE THREAD

**Issue by samherrmann** [shogowada/json-rpc-2.0#29]
From the README, it is not clear to me what the purpose is of `mapErrorToJSONRPCErrorResponse`. When should I register a `mapErrorToJSONRPCErrorResponse` function instead of creating a middleware?

## mapErrorToJSONRPCErrorResponse 
```ts
server.mapErrorToJSONRPCErrorResponse = (
  id: JSONRPCID,
  error: any
): JSONRPCErrorResponse => {
  return createJSONRPCErrorResponse(
    id,
    error?.code || 0,
    error?.message || 'An unexpected error occurred',
  );
};
```
## middleware
```ts
const exceptionMiddleware = async (next, request, serverParams) => {
  try {
    return await next(request, serverParams);
  } catch (error) {
    return createJSONRPCErrorResponse(
      request.id!, 
      error?.code || 0, 
      error?.message || 'An unexpected error occurred'
    );
  }
};

server.applyMiddleware(exceptionMiddleware);
```

**Comment by shogowada** [comment]
It's up to you; `mapErrorToJSONRPCErrorResponse` is designed for this specific use case, while middleware is more flexible and can do pretty much anything, which happens to include the error handling.

Let me know if you have more questions!
