### ISSUE TITLE
Compatibility with React Native / other backend languages?

### ISSUE THREAD

**Issue by princefishthrower** [shogowada/json-rpc-2.0#30]
First off, awesome library!

- Documentation 💯 
- Examples 💯 
- All TypeScript 💯 💯 💯 

So, on to my question, do you foresee anything in the implementation that would prevent this from working in React Native? It works on the web, so I would assume so. If you don't know I could just give it a try and report back 😄 

In terms of other backend languages, I suppose the client should also still work for backend frameworks other than Node (ex. .NET or Go) as long as we write a JSON RPC 2.0 compatible handler?

Thanks!

**Comment by shogowada** [comment]
Thank you for the kind words 😊

> do you foresee anything in the implementation that would prevent this from working in React Native? 

I don't think so. This library does not assume any protocol or platform.

> I suppose the client should also still work for backend frameworks other than Node (ex. .NET or Go) as long as we write a JSON RPC 2.0 compatible handler?

Yes 🙂 Please let me know if there was some compatibility issue!

**Comment by princefishthrower** [comment]
Awesome. Thanks for these answers! Now to find a nice library for Go... this one looks good: https://github.com/ybbus/jsonrpc but it works only HTTP... we'll see.

Thanks again!
