### ISSUE TITLE
Invalid JSON RPC request doesn't return expected result

### ISSUE THREAD

**Issue by chuacw** [shogowada/json-rpc-2.0#42]
If you send the following request:
`{"jsonrpc": "2.0", "method": "foobar, "params": "bar", "baz]`

according to the JSON RPC spec, it should return:
`{"jsonrpc": "2.0", "error": {"code": -32700, "message": "Parse error"}, "id": null}`

However, it returns the following:
```
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Error</title>
</head>
<body>
<pre>SyntaxError: Unexpected token } in JSON at position 95<br> &nbsp; &nbsp;at JSON.parse (&lt;anonymous&gt;)<br> &nbsp; &nbsp;at parse (K:\Development\TypeScript\InlineTypeGuard\node_modules\body-parser\lib\types\json.js:89:19)<br> &nbsp; &nbsp;at K:\Development\TypeScript\InlineTypeGuard\node_modules\body-parser\lib\read.js:128:18<br> &nbsp; &nbsp;at AsyncResource.runInAsyncScope (node:async_hooks:203:9)<br> &nbsp; &nbsp;at invokeCallback (K:\Development\TypeScript\InlineTypeGuard\node_modules\raw-body\index.js:231:16)<br> &nbsp; &nbsp;at done (K:\Development\TypeScript\InlineTypeGuard\node_modules\raw-body\index.js:220:7)<br> &nbsp; &nbsp;at IncomingMessage.onEnd (K:\Development\TypeScript\InlineTypeGuard\node_modules\raw-body\index.js:280:7)<br> &nbsp; &nbsp;at IncomingMessage.emit (node:events:513:28)<br> &nbsp; &nbsp;at IncomingMessage.emit (node:domain:489:12)<br> &nbsp; &nbsp;at endReadableNT (node:internal/streams/readable:1359:12)</pre>
</body>
</html>

```

See https://www.jsonrpc.org/specification#request_object for the "rpc call with invalid JSON" example

**Comment by shogowada** [comment]
Can you please share the minimal reproducible example? I believe the parsing part is happening in your code, not within the library.

**Comment by chuacw** [comment]
The parser I'm using is express.json(), so can you clarify if you're asking for a mre of the server, client, or both?

**Comment by shogowada** [comment]
In this case, so the parsing/error is happening in Express middleware, where this library has no control of.

If you want to use the library to parse JSON, please use `server.receiveJSON` method which takes a raw JSON string 😄
