### ISSUE TITLE
Client doesn't not support synchronous callback

### ISSUE THREAD

**Issue by jeiea** [shogowada/json-rpc-2.0#46]
I got the following exception with this. This is reproducible with android chrome webview and not with ios WkWebView.

```
caught (in promise) TypeError: Cannot read properties of undefined (reading 'then')
    at push../node_modules/json-rpc-2.0/dist/client.js.JSONRPCClient.requestAdvanced (client.js:145:1)
    at JSONRPCClient.<anonymous> (client.js:108:1)
    at step (client.js:33:1)
    at Object.next (client.js:14:46)
    at client.js:8:1
    at new Promise (<anonymous>)
    at push../node_modules/json-rpc-2.0/dist/client.js.__awaiter (client.js:4:1)
    at push../node_modules/json-rpc-2.0/dist/client.js.JSONRPCClient.requestWithID (client.js:102:1)
    at push../node_modules/json-rpc-2.0/dist/client.js.JSONRPCClient.request (client.js:99:1)
```

<img width="860" alt="image" src="https://user-images.githubusercontent.com/4188984/233520015-9c50ecbf-cb4c-4854-be29-94b7746b4645.png">

**Comment by shogowada** [comment]
So it looks like `this.send` is returning `undefined`.

This is the implementation of `this.send`: https://github.com/shogowada/json-rpc-2.0/blob/34e81d4840db166e97325f8c3cc30be5e958712a/src/client.ts#L225-L227

`this._send` is passed to the constructor: https://github.com/shogowada/json-rpc-2.0/blob/34e81d4840db166e97325f8c3cc30be5e958712a/src/client.ts#L46-L49

It looks like the function you are passing to the constructor is returning `undefined`.

How are you instantiating the `JSONRPCClient`?

**Comment by jeiea** [comment]
This is my implementation.

```javascript
class Wrapper {
  #client = new JSONRPCClient(async (request) => {
    this.#requestPort.postMessage(JSON.stringify(request));
  });

  share(url) {
    return this.#client.request('share', { url });
  }

  receive(result) {
    this.#client.receive(result);
  }
}
```

**Comment by shogowada** [comment]
OK, so `this.#requestPort.postMessage` is returning `undefined`?

**Comment by jeiea** [comment]
Maybe.

**Comment by shogowada** [comment]
Oh, you need to return:
```typescript
  #client = new JSONRPCClient((request) => {
    return this.#requestPort.postMessage(JSON.stringify(request));
  });
```

**Comment by jeiea** [comment]
I think that code have same problem. Why `JSONRPCClient` should receive asynchronous requester in constructor? I can't get it.

**Comment by shogowada** [comment]
Ah, I see what you mean. Yeah it can be synchronous. Send method now supports synchronous function. Please check [v1.6.0](https://github.com/shogowada/json-rpc-2.0/releases/tag/v1.6.0).

Thank you for the idea!
