### ISSUE TITLE
client receive function issue?

### ISSUE THREAD

**Issue by okaihc** [shogowada/json-rpc-2.0#5]
I'm pretty new to Javascript and Web development in general, currently learning to code with React and tried your project to run JSON-RPC 2.0 over websocket. Followed your JSONRPCServerAndClient example, but noticed that in code like this

       rpcServerClient.request("echo2", {"Hello": "hello"}).then(
        result => console.log("This function doesn't run for some reason"),
        error => console.error(`bad, error message = ${error.message}`)

line "result => console.log("This function doesn't run for some reason")," does not run.
BTW the React app is running in Safari browser. I don't know Typescript. I dug through the distributed javascript and patched the client.receive function like the following and it worked. Basically the response is coming in as a string so it had to be parsed into object first:

    JSONRPCClient.prototype.receive = function (response) {
        var parsed = JSON.parse(response);
        var resolve = this.idToResolveMap.get(parsed.id);
        if (resolve) {
            this.idToResolveMap.delete(parsed.id);
            resolve(parsed);
        }
    };
    return JSONRPCClient;

**Comment by shogowada** [comment]
Ah, thank you for reporting. I found an error on the WebSocket example.

This line:

```typescript
webSocket.onmessage = (event) => {
  serverAndClient.receiveAndSend(event.data.toString());
}
```

Should have been this:

```typescript
webSocket.onmessage = (event) => {
  serverAndClient.receiveAndSend(JSON.parse(event.data.toString()));
}
```

I have fixed the README. Can you please try?

**Comment by okaihc** [comment]
That worked. Thanks!
