### ISSUE TITLE
How to remove method added to server?

### ISSUE THREAD

**Issue by jeiea** [shogowada/json-rpc-2.0#50]
I'm finding a way to remove the method added by `server.addMethod(...)`, but it does not seem to exist.

I can recreate server and add methods from start, but I doubt I should do that.

Is there any way or will one be added? It would be nice to see this added like `const removeMethod = server.addMethod(...)`

**Comment by shogowada** [comment]
Yeah, I can create something like that. Can you share the use case please?

**Comment by jeiea** [comment]
I used this in react project and it was not convenient that making server to modify react state directly. So I made react component to add methods to server, and the component could be unmounted.

**Comment by shogowada** [comment]
It is released under [v1.7.0](https://github.com/shogowada/json-rpc-2.0/releases/tag/v1.7.0) ✨
