### ISSUE TITLE
Typed JSON RPC expects a index signature on "methods" type argument

### ISSUE THREAD

**Issue by nicojs** [shogowada/json-rpc-2.0#54]
The `TypedJSONRPCServer`  expects an index signature on the "methods" type argument. I don't think this should be the case, according to the docs.

![image](https://github.com/user-attachments/assets/69e94970-54ab-48e8-b4db-fdbe665c9dc1)

**Comment by shogowada** [comment]
Can you share how `MutationTestingServer` looks like?
