### ISSUE TITLE
The resolve is always undefined in the client's receive function

### ISSUE THREAD

**Issue by unnursolingimars** [shogowada/json-rpc-2.0#8]
![image](https://user-images.githubusercontent.com/55668228/92816829-783b3e00-f3b5-11ea-9c1c-00dcd1acc2a0.png)
I'm using the sample code for the client (using another json-rpc-2.0 API) but I won't get the Promise resolved when I'm sending the request. Do you have any idea what is wrong?

**Comment by shogowada** [comment]
Could it be the `id` being `string` vs. `number`? Can you see what `this.idToResolveMap` holds?

**Comment by unnursolingimars** [comment]
Aww YES! Thank you so much ! 
![bitmoji](https://sdk.bitmoji.com/render/panel/15f269e9-79ff-42f5-b6f8-df81e1cb3847-a886b0c0-d47c-4050-986c-548b371f41ab-v1.png?transparent=1&palette=1&width=246)
